import Foundation
import LiveStageModels

#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

// MARK: - Wire DTOs (the canonical wire schema, agreeing with the backend's TypeScript)

/// Start request body. Payload only — the server authors version/lastUpdatedAt/accepted_at.
struct StartRequest: Encodable {
    let templateId: String
    let deepLinkParameters: [String: String]
    let payload: TemplatePayload
}

struct StartResponse: Decodable {
    let sessionId: String
    let version: Int
    let deepLinkURL: String
    let staleAfterSeconds: Int
    let lastUpdatedAt: Date
}

/// Update request body. Payload only + the retry-safe clientMutationId.
struct UpdateRequest: Encodable {
    let clientMutationId: String
    let payload: TemplatePayload
}

struct UpdateResponse: Decodable {
    let version: Int
    let lastUpdatedAt: Date
    let state: LiveStageContentState
}

struct GetResponse: Decodable {
    let status: String
    let version: Int
    let lastUpdatedAt: Date
    let state: LiveStageContentState
    let staleAfterSeconds: Int
}

struct EndRequest: Encodable {
    let reason: String?
}

/// Batch event upload body (build spec §8.3). The response type lives in `EventUploader`.
struct BatchUploadRequest: Encodable {
    let events: [AnalyticsEvent]
}

struct APIErrorBody: Decodable {
    let error: String?
    let message: String?
    let field: String?
}

// MARK: - APIClient

/// Async REST client for the LiveStage backend (build spec §5.2). Adds the Bearer key, retries
/// transport/5xx failures with exponential backoff, and maps HTTP status → `LiveStageError`.
/// One `Idempotency-Key` per `start` and one `clientMutationId` per `update` are generated by the
/// runtime and reused across this client's retries, so a lost response can't double-write.
struct APIClient: Sendable {
    let baseURL: URL
    let apiKey: String
    var maxAttempts: Int = 4
    var session: URLSession = .shared

    func start(
        templateId: String,
        deepLinkParameters: [String: String],
        payload: TemplatePayload,
        idempotencyKey: String
    ) async throws -> StartResponse {
        let body = try Self.encoder.encode(StartRequest(
            templateId: templateId,
            deepLinkParameters: deepLinkParameters,
            payload: payload
        ))
        return try await send(path: "/v1/activities", method: "POST", body: body,
                              headers: ["Idempotency-Key": idempotencyKey])
    }

    func update(
        sessionId: String,
        clientMutationId: String,
        payload: TemplatePayload
    ) async throws -> UpdateResponse {
        let body = try Self.encoder.encode(UpdateRequest(clientMutationId: clientMutationId, payload: payload))
        return try await send(path: "/v1/activities/\(pathEscaped(sessionId))", method: "PATCH", body: body)
    }

    func get(sessionId: String) async throws -> GetResponse {
        try await send(path: "/v1/activities/\(pathEscaped(sessionId))", method: "GET", body: nil)
    }

    func end(sessionId: String, reason: String?) async throws {
        let body = try Self.encoder.encode(EndRequest(reason: reason))
        let _: EmptyResponse = try await send(
            path: "/v1/activities/\(pathEscaped(sessionId))/end", method: "POST", body: body
        )
    }

    func fetchConfiguration(templateId: String) async throws -> TemplateConfiguration {
        try await send(path: "/v1/templates/\(pathEscaped(templateId))", method: "GET", body: nil)
    }

    /// Uploads a batch of analytics events. The server dedupes by `eventId`, so a resend is safe.
    func uploadEvents(_ events: [AnalyticsEvent]) async throws -> BatchUploadResponse {
        let body = try Self.encoder.encode(BatchUploadRequest(events: events))
        return try await send(path: "/v1/events/batch", method: "POST", body: body)
    }

    // MARK: - Core request + retry

    private func send<T: Decodable>(
        path: String,
        method: String,
        body: Data?,
        headers: [String: String] = [:]
    ) async throws -> T {
        let (data, _) = try await perform(path: path, method: method, body: body, headers: headers)
        if data.isEmpty, let empty = EmptyResponse() as? T { return empty }
        do {
            return try Self.decoder.decode(T.self, from: data)
        } catch {
            throw LiveStageError.decoding(error)
        }
    }

    /// Performs the request with exponential backoff over transport errors and 5xx responses.
    /// 4xx are returned immediately as the mapped `LiveStageError` (no retry).
    private func perform(
        path: String,
        method: String,
        body: Data?,
        headers: [String: String]
    ) async throws -> (Data, HTTPURLResponse) {
        guard let url = URL(string: path, relativeTo: baseURL) else {
            throw LiveStageError.server(status: 0, message: "Bad URL for \(path)")
        }
        var request = URLRequest(url: url)
        request.httpMethod = method
        request.setValue("Bearer \(apiKey)", forHTTPHeaderField: "Authorization")
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        for (k, v) in headers { request.setValue(v, forHTTPHeaderField: k) }
        request.httpBody = body

        var lastError: Error = LiveStageError.network(underlying: URLError(.unknown))
        for attempt in 0..<maxAttempts {
            do {
                let (data, response) = try await session.data(for: request)
                guard let http = response as? HTTPURLResponse else {
                    throw LiveStageError.server(status: 0, message: "Non-HTTP response")
                }
                if http.statusCode >= 500 {
                    lastError = Self.mapError(status: http.statusCode, body: try? Self.decoder.decode(APIErrorBody.self, from: data))
                    if attempt < maxAttempts - 1 { try await backoff(attempt) }
                    continue
                }
                if http.statusCode >= 400 {
                    throw Self.mapError(status: http.statusCode, body: try? Self.decoder.decode(APIErrorBody.self, from: data))
                }
                return (data, http)
            } catch let error as LiveStageError {
                throw error  // mapped 4xx — do not retry
            } catch {
                lastError = LiveStageError.network(underlying: error)
                if attempt < maxAttempts - 1 { try await backoff(attempt) }
            }
        }
        throw lastError
    }

    private func backoff(_ attempt: Int) async throws {
        let seconds = pow(2.0, Double(attempt))           // 1s, 2s, 4s, ...
        try await Task.sleep(nanoseconds: UInt64(seconds * 1_000_000_000))
    }

    private func pathEscaped(_ value: String) -> String {
        value.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? value
    }

    // MARK: - Error mapping (pure, unit-tested)

    /// Maps an HTTP status (+ optional error body) to a `LiveStageError` (build spec §5.3).
    static func mapError(status: Int, body: APIErrorBody?) -> LiveStageError {
        switch status {
        case 400:
            return .validation(field: body?.field ?? "", message: body?.message ?? "Validation failed.")
        case 401, 403:
            return .server(status: status, message: body?.message ?? "Unauthorized.")
        case 404:
            return .sessionNotFound
        case 409:
            if body?.error == "already_ended" { return .alreadyEnded }
            return .server(status: 409, message: body?.message ?? "Conflict.")
        default:
            return .server(status: status, message: body?.message ?? "Unexpected response.")
        }
    }

    static let encoder = LiveStageJSON.encoder
    static let decoder = LiveStageJSON.decoder
}

/// Sentinel for endpoints that return no decodable body (e.g. `end`).
struct EmptyResponse: Decodable {}
